### ISSUE TITLE
Error re-running bionet build_env (removing output directory)

### ISSUE THREAD

**Issue by tmchartrand** [AllenInstitute/bmtk#36] opened 2018-10-01 19:24 UTC
In bionet, running a network multiple times (specifically, the ``build_env`` step) can give an error ``OSError: [Errno 39] Directory not empty: './output'``. Should be able to reproduce by simply opening an example ipynb and executing the "run" cell twice.
Seems to be an issue with Python's ``shutil.rmtree``, which should be able to delete non-empty directories but is failing in certain cases.
This is not hard to work around (just delete manually), but slightly annoying - I'm curious if it's specific to my installation or if others have seen it too (I'm using Anaconda Python 2.7.15).

Note that this doesn't occur from simply running ``run_bionet.py`` twice, but it's also not restricted to jupyter or ipython (can reproduce by executing the relevant lines directly in a python console. Strange!

**Comment by kaeldai** [comment] 2018-10-01 20:05
Hi @tmchartrand - When this happens next time can you look to see if there is a .nsf000* file in the output dir?

**Comment by tmchartrand** [comment] 2018-10-01 20:29
yes indeed - so it's something related to running on a network drive?

**Comment by kaeldai** [comment] 2021-04-02 17:57
Issue is being caused by a posix file-lock, closing.

**Closed as completed by kaeldai** 2021-04-02 17:57 UTC
